### ISSUE TITLE
unit test failure: testSafariGetsHTML null expected:<[text/html]> but was:<[application/x-turtle]>

### ISSUE THREAD

**Issue by jgeluk** [cygri/pubby#27]
testSafariGetsHTML(de.fuberlin.wiwiss.pubby.negotiation.PubbyNegotiatorTest)  Time elapsed: 0.001 sec  <<< FAILURE!
junit.framework.ComparisonFailure: null expected:<[text/html]> but was:<[application/x-turtle]>
    at junit.framework.Assert.assertEquals(Assert.java:81)
    at junit.framework.Assert.assertEquals(Assert.java:87)
    at de.fuberlin.wiwiss.pubby.negotiation.PubbyNegotiatorTest.testSafariGetsHTML(PubbyNegotiatorTest.java:72)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at junit.framework.TestCase.runTest(TestCase.java:168)
    at junit.framework.TestCase.runBare(TestCase.java:134)
    at junit.framework.TestResult$1.protect(TestResult.java:110)
    at junit.framework.TestResult.runProtected(TestResult.java:128)
    at junit.framework.TestResult.run(TestResult.java:113)
    at junit.framework.TestCase.run(TestCase.java:124)
    at junit.framework.TestSuite.runTest(TestSuite.java:232)
    at junit.framework.TestSuite.run(TestSuite.java:227)
    at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:79)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**Comment by pirelaurent** [comment]
**\* i'm here because these errors prevent _mvn package_ to progress and to obtain a  war **\* 
_After a look, the errors come from_    negotiator.getBestMatch("*/*")   in 
- testAcceptEverythingGetsHTML  
- testSafariGetsHTML.

_Digging into PubbyNegociator.java found the note :_ 
--Send Turtle to clients that indicate they accept everything.-- 
...  pubbyNegotiator.addUserAgentOverride(null,"*/*", "text/turtle");

_So it is designed now to return [application/x-turtle] when_ "*/*"  only
*\* Class is ok, test is not **
=> either change the assert assertEquals("text/html",   by "application/x-turtle"
=> either comment the two tests. 

HTH

**Comment by sorenroug** [comment]
I have the same issue. I can see these tests are from 2007, while the modification in PubbyNegotiator.java that causes the tests to fail is from October 2013.

**Comment by sorenroug** [comment]
I have contributed a patch that fixes the tests. Richard just have to pull it.
